type ItemType = 'coffee'|'tea'|'milk'|'croissant'|'cake'|'cookie'|'fish'|'dessert'|'sugarBomb'|'goldenFish'|'coffeeBoost';
type Screen = 'menu'|'gameplay'|'pause'|'results'|'shop'|'settings'|'leaderboard'|'tutorial';
type Mood = 'waiting'|'happy'|'impatient'|'served';
type CatKind = 'orange'|'gray'|'white'|'black'|'tabby';
type Item = { id:number; type:ItemType; gx:number; gy:number; x:number; y:number; tx:number; ty:number; selected:boolean; scale:number; born:number };
type Need = { type:ItemType; qty:number; got:number };
type Order = { needs:Need[]; coins:number; score:number; patience:number; maxPatience:number; done:boolean };
type Customer = { id:number; name:string; kind:CatKind; mood:Mood; order:Order; servedMs:number };
type Button = { id:string; text:string; x:number; y:number; w:number; h:number; enabled?:boolean; tag?:string };
type Float = { text:string; x:number; y:number; life:number; color:string };
type Particle = { x:number; y:number; vx:number; vy:number; life:number; kind:'heart'|'coin'|'spark' };
type Save = { coins:number; best:number; day:number; tutorial:boolean; sound:boolean; vibration:boolean; quality:'low'|'medium'|'high'; upgrades:Record<string,number>; boosters:Record<string,number>; daily:string };

declare global { interface Window { YaGames?: any } }

const BASIC:ItemType[]=['coffee','tea','milk','croissant','cake','cookie','fish','dessert'];
const names=['Рыжик','Белла','Мурзик','Пуша','Барсик','Снежок','Тигра','Латте'];
const catKinds:CatKind[]=['orange','gray','white','black','tabby'];
const itemName:Record<ItemType,string>={coffee:'Кофе',tea:'Чай',milk:'Молоко',croissant:'Круассан',cake:'Пирожное',cookie:'Печенье',fish:'Рыба',dessert:'Десерт',sugarBomb:'Сахарок',goldenFish:'Золотая рыбка',coffeeBoost:'Буст'};
const upgradeTitles:Record<string,string>={coffee:'Быстрая кофемашина',tables:'Уютные столики',dessert:'Витрина десертов',barista:'Помощник-бариста',magnet:'Магнит лакомств',bowls:'Премиум миски'};
let uid=1;

function pick<T>(a:T[]){ return a[Math.floor(Math.random()*a.length)] }
function clamp(v:number,a:number,b:number){ return Math.max(a,Math.min(b,v)) }
function lerp(a:number,b:number,t:number){ return a+(b-a)*t }
function today(){ return new Date().toISOString().slice(0,10) }
function rr(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function ellipse(ctx:CanvasRenderingContext2D,x:number,y:number,rx:number,ry:number,fill:string|CanvasGradient,rot=0){ctx.fillStyle=fill;ctx.beginPath();ctx.ellipse(x,y,rx,ry,rot,0,Math.PI*2);ctx.fill()}

export class Game{
  canvas:HTMLCanvasElement; ctx:CanvasRenderingContext2D; w=390; h=844; dpr=1; screen:Screen='menu'; last=0; sdk:any=null;
  board:Item[][]=[]; chain:Item[]=[]; drag=false; buttons:Button[]=[]; floats:Float[]=[]; particles:Particle[]=[];
  score=0; runCoins=0; combo=0; served=0; time=60; extraUsed=false; slow=1; leaderboard:any[]=[]; tut=0;
  save:Save=this.load(); cats:Customer[]=[];
  audio?:AudioContext;
  constructor(canvas:HTMLCanvasElement){this.canvas=canvas;this.ctx=canvas.getContext('2d')!;}
  async boot(){await this.initYandex();this.resize();addEventListener('resize',()=>this.resize());document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.screen==='gameplay'){this.screen='pause';this.stopGameplay()}});this.bind();this.dailyBonus();this.ready();requestAnimationFrame(t=>this.loop(t));}
  bind(){const p=(e:PointerEvent)=>{const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};this.canvas.addEventListener('pointerdown',e=>{e.preventDefault();const m=p(e);if(this.hit(m.x,m.y))return;if(this.screen!=='gameplay')return;const it=this.cellAt(m.x,m.y);if(it){this.drag=true;this.chain=[it];it.selected=true;this.tone(520,.035)}});this.canvas.addEventListener('pointermove',e=>{if(!this.drag||this.screen!=='gameplay')return;const m=p(e),it=this.cellAt(m.x,m.y),last=this.chain[this.chain.length-1],prev=this.chain[this.chain.length-2];if(!it||!last)return;if(it===prev){last.selected=false;this.chain.pop();return}if(it!==last&&!it.selected&&this.neighbor(it,last)&&(it.type===last.type||it.type==='goldenFish'||last.type==='goldenFish')){it.selected=true;this.chain.push(it);this.tone(620,.025)}});addEventListener('pointerup',()=>{if(!this.drag)return;this.drag=false;this.resolveChain();for(const it of this.chain)it.selected=false;this.chain=[]});this.canvas.addEventListener('contextmenu',e=>e.preventDefault())}
  resize(){this.dpr=Math.min(devicePixelRatio||1,2);this.w=innerWidth;this.h=innerHeight;this.canvas.width=Math.floor(this.w*this.dpr);this.canvas.height=Math.floor(this.h*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.layoutBoard()}
  load():Save{try{const raw=localStorage.getItem('catcafe_save_v2');if(raw)return{coins:120,best:0,day:1,tutorial:false,sound:true,vibration:true,quality:'high',upgrades:{coffee:0,tables:0,dessert:0,barista:0,magnet:0,bowls:0},boosters:{hint:3,mix:3,boost:3},daily:'',...JSON.parse(raw)}}catch{}return{coins:120,best:0,day:1,tutorial:false,sound:true,vibration:true,quality:'high',upgrades:{coffee:0,tables:0,dessert:0,barista:0,magnet:0,bowls:0},boosters:{hint:3,mix:3,boost:3},daily:''}}
  persist(){localStorage.setItem('catcafe_save_v2',JSON.stringify(this.save));try{this.sdk?.player?.setData?.(this.save,true)}catch{}}
  dailyBonus(){if(this.save.daily!==today()){this.save.daily=today();this.save.coins+=50;this.floats.push({text:'+50 ежедневный бонус',x:this.w/2,y:210,life:1800,color:'#ffe35c'});this.persist()}}
  async initYandex(){try{if(window.YaGames){this.sdk=await window.YaGames.init();try{this.sdk.player=await this.sdk.getPlayer()}catch{}}}catch{this.sdk=null}}
  ready(){try{this.sdk?.features?.LoadingAPI?.ready?.()}catch{}}
  startGameplay(){try{this.sdk?.features?.GameplayAPI?.start?.()}catch{}}
  stopGameplay(){try{this.sdk?.features?.GameplayAPI?.stop?.()}catch{}}
  rewarded(fn:()=>void){try{if(!this.sdk){fn();return}this.stopGameplay();this.sdk.adv.showRewardedVideo({callbacks:{onRewarded:fn,onClose:()=>this.startGameplay(),onError:()=>this.startGameplay()}})}catch{fn()}}
  interstitial(){try{if(this.sdk)this.sdk.adv.showFullscreenAdv({callbacks:{onClose:()=>{},onError:()=>{}}})}catch{}}
  levelItems(){const d=this.save.day,a:ItemType[]=['coffee','tea','milk'];if(d>=2)a.push('cookie');if(d>=3)a.push('croissant');if(d>=5)a.push('fish');if(d>=7)a.push('cake');if(d>=15)a.push('dessert');return a}
  level(){const day=this.save.day;return{duration:day<=2?60:75,customers:day>=10?3:day>=4?3:2,patience:Math.max(16,34-Math.floor(day*.7)),complex:day>=4?Math.min(.75,.22+day*.025):0,slots:day>=20?3:day>=4?2:1}}
  layoutBoard(){const top=this.h<720?185:238;const cell=Math.min((this.w-34)/6,(this.h-top-132)/6);const ox=(this.w-cell*6)/2,oy=top;for(const it of this.items()){it.tx=ox+it.gx*cell+cell/2;it.ty=oy+it.gy*cell+cell/2;if(!it.x&&!it.y){it.x=it.tx;it.y=it.ty}}}
  boardMetrics(){const top=this.h<720?185:238;const cell=Math.min((this.w-34)/6,(this.h-top-132)/6);return{cell,ox:(this.w-cell*6)/2,oy:top,size:cell*6}}
  randType(){const r=Math.random(),bonus=.012+(this.save.upgrades.magnet||0)*.004;if(r<bonus)return'goldenFish' as ItemType;if(r<bonus*1.55)return'coffeeBoost' as ItemType;return pick(this.levelItems())}
  makeItem(gx:number,gy:number,x=0,y=0):Item{return{id:uid++,type:this.randType(),gx,gy,x,y,tx:x,ty:y,selected:false,scale:.2,born:performance.now()}}
  initBoard(){this.board=[];for(let y=0;y<6;y++){this.board[y]=[];for(let x=0;x<6;x++)this.board[y][x]=this.makeItem(x,y)}this.layoutBoard()}
  items(){return this.board.flat().filter(Boolean)}
  cellAt(px:number,py:number){const b=this.boardMetrics(),gx=Math.floor((px-b.ox)/b.cell),gy=Math.floor((py-b.oy)/b.cell);return gx>=0&&gx<6&&gy>=0&&gy<6?this.board[gy][gx]:null}
  neighbor(a:Item,b:Item){return Math.abs(a.gx-b.gx)<=1&&Math.abs(a.gy-b.gy)<=1&&a!==b}
  order():Order{const l=this.level(),needs:Need[]=[],pool=[...this.levelItems()];const count=Math.random()<l.complex?Math.min(l.slots,2+(Math.random()<.25?1:0)):1;for(let i=0;i<count;i++){const t=pick(pool);pool.splice(pool.indexOf(t),1);needs.push({type:t,qty:1+Math.floor(Math.random()*(this.save.day<4?2:3)),got:0})}const dessert=needs.some(n=>n.type==='cake'||n.type==='dessert'),fish=needs.some(n=>n.type==='fish'),coffee=needs.some(n=>n.type==='coffee');let coins=12+needs.reduce((a,n)=>a+n.qty*6,0)+count*8;if(dessert)coins+=(this.save.upgrades.dessert||0)*3;if(fish)coins+=(this.save.upgrades.bowls||0)*3;let score=100+needs.reduce((a,n)=>a+n.qty*18,0)+(coffee?(this.save.upgrades.coffee||0)*20:0);let pat=l.patience+(this.save.upgrades.tables||0)*2+count*4;return{needs,coins,score,patience:pat,maxPatience:pat,done:false}}
  makeCat():Customer{return{id:uid++,name:pick(names),kind:pick(catKinds),mood:'waiting',order:this.order(),servedMs:0}}
  start(){this.score=0;this.runCoins=0;this.combo=0;this.served=0;this.time=this.level().duration;this.slow=1;this.extraUsed=false;this.floats=[];this.particles=[];this.initBoard();this.cats=[];for(let i=0;i<this.level().customers;i++)this.cats.push(this.makeCat());this.screen=this.save.tutorial?'gameplay':'tutorial';this.startGameplay();this.tone(420,.08)}
  loop(t:number){const dt=Math.min(33,t-this.last||16);this.last=t;this.update(dt);this.render(t);requestAnimationFrame(tt=>this.loop(tt))}
  update(dt:number){for(const it of this.items()){it.x=lerp(it.x,it.tx,.22);it.y=lerp(it.y,it.ty,.22);it.scale=lerp(it.scale,it.selected?1.13:1,.12)}if(this.screen==='gameplay'){this.time-=dt/1000;if(this.slow<1)this.slow=Math.min(1,this.slow+dt/10000);for(let i=this.cats.length-1;i>=0;i--){const c=this.cats[i];if(c.mood==='served'){c.servedMs+=dt;if(c.servedMs>850){this.cats.splice(i,1);this.cats.push(this.makeCat())}continue}c.order.patience-=dt/1000*this.slow;c.mood=c.order.patience<c.order.maxPatience*.25?'impatient':'waiting';if(c.order.patience<=0){this.float(c.name+' ушёл',this.w/2,170,'#ff6565');this.combo=0;this.cats.splice(i,1);this.cats.push(this.makeCat())}}if(this.time<=0)this.finish()}for(const f of this.floats){f.life-=dt;f.y-=dt*.045}this.floats=this.floats.filter(f=>f.life>0);for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.vy+=.035*dt/16}this.particles=this.particles.filter(p=>p.life>0)}
  finish(){this.screen='results';this.stopGameplay();this.save.coins+=this.runCoins;if(this.score>this.save.best){this.save.best=this.score;try{this.sdk?.leaderboards?.setLeaderboardScore?.('cat_cafe_score',this.score)}catch{}}if(this.served>0)this.save.day++;this.persist();this.interstitial()}
  resolveChain(){if(this.chain.length<3){this.tone(160,.08,'sawtooth');return}const type=this.chain.find(i=>i.type!=='goldenFish')?.type||this.chain[0].type;let points=this.chain.length*10+(this.chain.length>=4?20:0)+(this.chain.length>=5?50:0);points=Math.round(points*(1+Math.floor(this.combo/3)*.2));let left=this.chain.length;for(const c of this.cats){if(c.mood==='served')continue;for(const n of c.order.needs){if((n.type===type||type==='goldenFish')&&n.got<n.qty&&left>0){const add=Math.min(n.qty-n.got,left);n.got+=add;left-=add}}c.order.done=c.order.needs.every(n=>n.got>=n.qty);if(c.order.done){c.mood='served';c.servedMs=0;this.combo++;this.served++;points+=c.order.score+Math.round(50*c.order.patience/c.order.maxPatience);this.runCoins+=c.order.coins+this.combo;this.float('Мяу-комбо! +' + c.order.coins + ' 🪙',this.w/2,178,'#ffe35c');this.hearts(this.w/2,178);this.tone(840,.11)}}this.score+=points;this.float('+'+points,this.chain[0].x,this.chain[0].y,'#fff25e');const special=this.chain.length>=6?this.chain[Math.floor(this.chain.length/2)]:null;for(const it of this.chain)this.board[it.gy][it.gx]=null as any;this.collapse();if(special){const it=this.cellAt(special.tx,special.ty);if(it)it.type='sugarBomb'}if(navigator.vibrate&&this.save.vibration)navigator.vibrate(24)}
  collapse(){const b=this.boardMetrics();for(let x=0;x<6;x++){let w=5;for(let y=5;y>=0;y--){const it=this.board[y][x];if(it){this.board[w][x]=it;it.gx=x;it.gy=w;it.tx=b.ox+x*b.cell+b.cell/2;it.ty=b.oy+w*b.cell+b.cell/2;if(y!==w)this.board[y][x]=null as any;w--}}for(let y=w;y>=0;y--){const it=this.makeItem(x,y,b.ox+x*b.cell+b.cell/2,b.oy+(y-w-2)*b.cell);it.tx=b.ox+x*b.cell+b.cell/2;it.ty=b.oy+y*b.cell+b.cell/2;this.board[y][x]=it}}}
  hit(x:number,y:number){const b=this.buttons.find(q=>q.enabled!==false&&x>=q.x&&x<=q.x+q.w&&y>=q.y&&y<=q.y+q.h);if(!b){if(this.screen==='tutorial'){this.tut++;if(this.tut>3){this.save.tutorial=true;this.persist();this.screen='gameplay'}}return false}this.tone(330,.04);if(b.id==='play')this.start();else if(b.id==='menu'){this.screen='menu';this.stopGameplay()}else if(b.id==='pause'){this.screen='pause';this.stopGameplay()}else if(b.id==='resume'){this.screen='gameplay';this.startGameplay()}else if(b.id==='shop')this.screen='shop';else if(b.id==='settings')this.screen='settings';else if(b.id==='leaderboard'){this.leaderboard=[];this.screen='leaderboard'}else if(b.id==='sound'){this.save.sound=!this.save.sound;this.persist()}else if(b.id==='vibration'){this.save.vibration=!this.save.vibration;this.persist()}else if(b.id==='quality'){this.save.quality=this.save.quality==='high'?'medium':this.save.quality==='medium'?'low':'high';this.persist()}else if(b.id==='buy'&&b.tag)this.buy(b.tag);else if(b.id==='mix'){if(this.save.boosters.mix>0){this.save.boosters.mix--;const types=this.items().map(i=>i.type).sort(()=>Math.random()-.5);this.items().forEach((i,n)=>i.type=types[n]);this.persist()}}else if(b.id==='boost'){if(this.save.boosters.boost>0){this.save.boosters.boost--;this.slow=.45;this.persist()}}else if(b.id==='hint')this.hint();else if(b.id==='x2')this.rewarded(()=>{this.save.coins+=this.runCoins;this.runCoins=0;this.persist()});else if(b.id==='extra'&&!this.extraUsed)this.rewarded(()=>{this.time+=20;this.extraUsed=true});return true}
  buy(k:string){const lvl=this.save.upgrades[k]||0,price=60*(lvl+1)*(lvl+1);if(lvl>=5||this.save.coins<price)return;this.save.coins-=price;this.save.upgrades[k]=lvl+1;this.persist()}
  hint(){if(this.save.boosters.hint<=0)return;this.save.boosters.hint--;for(const it of this.items()){const near=this.items().filter(o=>o.type===it.type&&this.neighbor(it,o));if(near.length>=2){it.selected=near[0].selected=near[1].selected=true;setTimeout(()=>{it.selected=near[0].selected=near[1].selected=false},900);break}}this.persist()}
  float(text:string,x:number,y:number,color='#fff25e'){this.floats.push({text,x,y,life:1000,color})}
  hearts(x:number,y:number){for(let i=0;i<12;i++)this.particles.push({x,y,vx:(Math.random()-.5)*4,vy:-2-Math.random()*2,life:850,kind:i%3?'heart':'coin'})}
  tone(freq:number,dur=.06,type:OscillatorType='sine'){if(!this.save.sound)return;try{const AC=window.AudioContext||(window as any).webkitAudioContext;if(!this.audio&&AC)this.audio=new AC();if(!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.05;o.connect(g);g.connect(this.audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+dur);o.stop(this.audio.currentTime+dur)}catch{}}

  render(t:number){this.buttons=[];this.bg(t);if(this.screen==='menu')this.menu();else if(this.screen==='gameplay'||this.screen==='tutorial')this.gameplay(t);else if(this.screen==='pause')this.pause();else if(this.screen==='results')this.results();else if(this.screen==='shop')this.shop();else if(this.screen==='settings')this.settings();else if(this.screen==='leaderboard')this.records();this.drawButtons();this.effects()}
  bg(t:number){const c=this.ctx,g=c.createLinearGradient(0,0,0,this.h);g.addColorStop(0,'#f8cf91');g.addColorStop(.46,'#ffe9c8');g.addColorStop(1,'#d78d4a');c.fillStyle=g;c.fillRect(0,0,this.w,this.h);c.fillStyle='rgba(122,69,31,.18)';for(let y=this.h*.53;y<this.h;y+=42)c.fillRect(0,y,this.w,2);for(let x=-60;x<this.w;x+=86)c.fillRect(x,this.h*.53,2,this.h*.47);c.fillStyle='rgba(255,247,194,.38)';c.beginPath();c.arc(this.w*.78,this.h*.16,95,0,7);c.fill();c.strokeStyle='rgba(116,65,31,.35)';c.lineWidth=8;c.stroke();c.fillStyle='rgba(255,244,190,.28)';c.beginPath();c.moveTo(this.w*.78,this.h*.16);c.lineTo(this.w,this.h*.66);c.lineTo(this.w*.55,this.h*.66);c.closePath();c.fill();for(const x of [this.w*.22,this.w*.5,this.w*.78]){c.strokeStyle='#8b5529';c.lineWidth=5;c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h*.12);c.stroke();ellipse(c,x,this.h*.14,36,18,'#f3b94d');c.fillStyle='rgba(255,235,150,.28)';c.beginPath();c.arc(x,this.h*.17+Math.sin(t*.002+x)*3,68,0,7);c.fill()}c.fillStyle='rgba(110,62,28,.34)';c.fillRect(0,this.h*.31,this.w,this.h*.085);this.panel(this.w*.05,this.h*.34,this.w*.9,this.h*.12,24);c.fillStyle='#75411f';c.font='800 18px Arial';c.textAlign='left';c.fillText('Кофе • Лакомства • Котики',26,this.h*.38);c.fillStyle='rgba(68,124,62,.36)';for(let i=0;i<6;i++)ellipse(c,18+i*12,this.h-62-Math.sin(t*.003+i)*8,12,26,'rgba(68,124,62,.36)',i*.7)}
  panel(x:number,y:number,w:number,h:number,r=22){const c=this.ctx;c.save();ellipse(c,x+w/2,y+h+9,w*.42,14,'rgba(70,38,14,.18)');const g=c.createLinearGradient(x,y,x,y+h);g.addColorStop(0,'#fff2d7');g.addColorStop(1,'#ffd28d');rr(c,x,y,w,h,r);c.fillStyle=g;c.fill();c.strokeStyle='rgba(112,58,20,.25)';c.lineWidth=2;c.stroke();c.fillStyle='rgba(255,255,255,.27)';rr(c,x+6,y+6,w-12,h*.32,r*.65);c.fill();c.restore()}
  button(id:string,text:string,x:number,y:number,w:number,h:number,enabled=true,tag?:string){this.buttons.push({id,text,x,y,w,h,enabled,tag})}
  drawButtons(){for(const b of this.buttons){const c=this.ctx;c.save();ellipse(c,b.x+b.w/2,b.y+b.h+5,b.w*.36,12,'rgba(70,38,14,.18)');const g=c.createLinearGradient(b.x,b.y,b.x,b.y+b.h);g.addColorStop(0,b.enabled!==false?'#9eef76':'#d5c4aa');g.addColorStop(1,b.enabled!==false?'#3fae3c':'#a99680');rr(c,b.x,b.y,b.w,b.h,18);c.fillStyle=g;c.fill();c.strokeStyle='rgba(83,45,17,.28)';c.lineWidth=2;c.stroke();c.fillStyle='#fff';c.textAlign='center';c.textBaseline='middle';c.font=`900 ${Math.round(b.h*.35)}px Arial`;c.strokeStyle='rgba(83,45,17,.35)';c.lineWidth=4;c.strokeText(b.text,b.x+b.w/2,b.y+b.h/2);c.fillText(b.text,b.x+b.w/2,b.y+b.h/2);c.restore()}}
  logo(y:number){const c=this.ctx;c.textAlign='center';c.font='900 44px Arial';c.strokeStyle='rgba(75,38,16,.35)';c.lineWidth=7;c.strokeText('Котокафе',this.w/2,y);c.fillStyle='#77401e';c.fillText('Котокафе',this.w/2,y);c.font='800 21px Arial';c.fillStyle='#d85e7f';c.fillText('Match & Serve',this.w/2,y+34)}
  menu(){this.logo(120);const c=this.ctx;c.textAlign='center';c.fillStyle='#6d3b1f';c.font='800 20px Arial';c.fillText(`День ${this.save.day}   🪙 ${this.save.coins}   Рекорд ${this.save.best}`,this.w/2,184);this.button('play','Играть',this.w/2-100,232,200,62);this.button('shop','Улучшения',this.w/2-100,310,200,54);this.button('leaderboard','Рекорды',this.w/2-100,374,200,54);this.button('settings','Настройки',this.w/2-100,438,200,54);this.panel(26,520,this.w-52,86,22);c.font='17px Arial';c.fillStyle='#7a4724';c.fillText('Соединяй 3+ одинаковых лакомства',this.w/2,555);c.fillText('и выполняй заказы милых котиков!',this.w/2,582)}
  gameplay(t:number){this.hud();const gap=this.w/(this.cats.length+1);this.cats.forEach((cat,i)=>this.cat(gap*(i+1)-48,98,cat,t));this.drawBoard();const y=this.h-90;this.button('hint','Подсказка',22,y,104,56,this.save.boosters.hint>0);this.button('mix','Микс',this.w/2-52,y,104,56,this.save.boosters.mix>0);this.button('boost','Буст',this.w-126,y,104,56,this.save.boosters.boost>0);this.button('pause','Ⅱ',this.w-58,24,42,40);if(!this.extraUsed&&this.time<12)this.button('extra','+20 сек',this.w/2-54,y-66,108,48);if(this.screen==='tutorial')this.tutorial()}
  hud(){this.panel(12,10,this.w-24,62,18);const c=this.ctx;c.fillStyle='#6d3b1f';c.font='900 20px Arial';c.textAlign='left';c.fillText(`★ ${this.score}`,28,47);c.fillText(`⏱ ${Math.ceil(this.time)}`,this.w*.28,47);c.fillText(`🪙 ${this.save.coins+this.runCoins}`,this.w*.50,47);c.fillText(`x${Math.max(1,this.combo)}`,this.w*.71,47);c.textAlign='right';c.fillText(`День ${this.save.day}`,this.w-26,47);this.progress(28,64,this.w-56,8,this.time/this.level().duration,'#72d852')}
  drawBoard(){const b=this.boardMetrics(),c=this.ctx;this.panel(b.ox-8,b.oy-8,b.size+16,b.size+16,25);for(let y=0;y<6;y++)for(let x=0;x<6;x++){c.fillStyle=(x+y)%2?'rgba(255,247,224,.58)':'rgba(255,255,255,.43)';rr(c,b.ox+x*b.cell+3,b.oy+y*b.cell+3,b.cell-6,b.cell-6,14);c.fill()}if(this.chain.length>1){c.strokeStyle='rgba(255,211,55,.92)';c.lineWidth=8;c.lineCap='round';c.lineJoin='round';c.beginPath();this.chain.forEach((it,i)=>i?c.lineTo(it.x,it.y):c.moveTo(it.x,it.y));c.stroke();c.strokeStyle='rgba(255,255,255,.88)';c.lineWidth=3;c.stroke()}for(const it of this.items()){if(it.selected){c.save();c.shadowColor='#45baff';c.shadowBlur=18;c.fillStyle='rgba(71,188,255,.24)';rr(c,it.x-b.cell*.43,it.y-b.cell*.43,b.cell*.86,b.cell*.86,18);c.fill();c.restore()}this.item(it.type,it.x,it.y,Math.min(.95,it.scale)*(b.cell/74))}}
  progress(x:number,y:number,w:number,h:number,t:number,col:string){const c=this.ctx;rr(c,x,y,w,h,h/2);c.fillStyle='#7a4826';c.fill();rr(c,x+2,y+2,(w-4)*clamp(t,0,1),h-4,h/2);const g=c.createLinearGradient(x,y,x,y+h);g.addColorStop(0,'#eaff96');g.addColorStop(1,col);c.fillStyle=g;c.fill()}
  item(type:ItemType,x:number,y:number,s=1){const c=this.ctx;c.save();c.scale(s,s);x/=s;y/=s;ellipse(c,x,y+26,48,15,'rgba(58,34,15,.2)');if(type==='coffee'){this.cup(x,y,'#f7f0de','#5b321f');c.strokeStyle='#f7f0de';c.lineWidth=5;c.beginPath();c.arc(x+27,y-4,11,-1.2,1.2);c.stroke();this.steam(x,y)}else if(type==='tea'){this.cup(x,y,'#87d985','#2d7c45');c.strokeStyle='#5fb56a';c.lineWidth=5;c.beginPath();c.arc(x+26,y-4,11,-1.2,1.2);c.stroke();ellipse(c,x-8,y-17,7,4,'#9ee883',-.5)}else if(type==='milk'){const g=c.createLinearGradient(x-18,y-30,x+18,y+30);g.addColorStop(0,'#ffffff');g.addColorStop(1,'#aee9ff');rr(c,x-19,y-31,38,62,9);c.fillStyle=g;c.fill();c.strokeStyle='#69aac7';c.lineWidth=2;c.stroke();ellipse(c,x,y-32,19,6,'#fff');c.fillStyle='#fff';rr(c,x-11,y-14,22,24,5);c.fill();c.fillStyle='#5bb7df';c.font='800 10px Arial';c.textAlign='center';c.fillText('MILK',x,y)}else if(type==='croissant'){for(let i=0;i<5;i++){const g=c.createLinearGradient(x-32+i*16,y-22,x-22+i*16,y+20);g.addColorStop(0,'#ffe08a');g.addColorStop(1,'#c67626');ellipse(c,x-28+i*14,y+Math.abs(i-2)*5,18,28,g,(i-2)*.45)}c.strokeStyle='#9b541e';c.lineWidth=2;c.beginPath();c.arc(x,y+4,39,.15,Math.PI-.15);c.stroke()}else if(type==='cake'){rr(c,x-27,y-5,54,33,6);c.fillStyle='#f5c07b';c.fill();c.fillStyle='#fff5eb';c.beginPath();c.moveTo(x-27,y-5);c.lineTo(x+27,y-5);c.lineTo(x+8,y+10);c.lineTo(x-27,y+10);c.fill();c.fillStyle='#ee4b68';c.beginPath();c.moveTo(x+27,y-5);c.lineTo(x+8,y+10);c.lineTo(x-4,y+28);c.lineTo(x+27,y+28);c.fill();ellipse(c,x+7,y-22,10,8,'#e93550');ellipse(c,x+15,y-29,8,4,'#43a952',-.4)}else if(type==='cookie'){const g=c.createRadialGradient(x-10,y-12,2,x,y,31);g.addColorStop(0,'#ffdb86');g.addColorStop(1,'#c97932');ellipse(c,x,y,28,26,g);c.strokeStyle='#8b4d22';c.lineWidth=2;c.stroke();for(const p of [[-10,-7],[8,-9],[12,8],[-5,12],[-16,7]])ellipse(c,x+p[0],y+p[1],5,5,'#673519')}else if(type==='fish'||type==='goldenFish'){const g=c.createLinearGradient(x-25,y-16,x+25,y+16);g.addColorStop(0,type==='goldenFish'?'#fff38d':'#8de6ff');g.addColorStop(1,type==='goldenFish'?'#ffb725':'#2278c6');ellipse(c,x,y,27,18,g);c.fillStyle=type==='goldenFish'?'#ffb725':'#2b83d1';c.beginPath();c.moveTo(x+22,y);c.lineTo(x+43,y-17);c.lineTo(x+39,y+17);c.fill();ellipse(c,x-10,y-5,5,6,'#fff');ellipse(c,x-9,y-5,2.5,3,'#1d2530')}else if(type==='dessert'){rr(c,x-24,y-8,48,31,9);c.fillStyle='#e7f9ff';c.fill();c.strokeStyle='#87b7c2';c.stroke();ellipse(c,x,y-10,26,13,'#fff8f2');ellipse(c,x,y-3,22,8,'#ff4e66');ellipse(c,x-5,y-21,12,9,'#ec3347');ellipse(c,x+9,y-30,8,4,'#3da94d',-.2)}else if(type==='sugarBomb'){ellipse(c,x,y,24,24,'#e9739a');c.strokeStyle='#633';c.lineWidth=3;c.stroke();c.fillStyle='#fff0f2';for(let i=0;i<7;i++)ellipse(c,x-13+i*4,y-4+Math.sin(i)*8,5,5,'#fff0f2')}else if(type==='coffeeBoost'){rr(c,x-18,y-27,36,56,10);c.fillStyle='#58bbb6';c.fill();ellipse(c,x,y-27,19,7,'#4d2c1c');c.fillStyle='#fff';c.font='900 20px Arial';c.textAlign='center';c.fillText('↯',x,y+10)}c.restore()}
  cup(x:number,y:number,ceramic:string,liquid:string){const c=this.ctx;const g=c.createLinearGradient(x-24,y-20,x+25,y+25);g.addColorStop(0,ceramic);g.addColorStop(1,'#d9c5a6');rr(c,x-25,y-18,50,42,10);c.fillStyle=g;c.fill();c.strokeStyle='rgba(92,50,25,.35)';c.lineWidth=2;c.stroke();ellipse(c,x,y-18,26,9,liquid);c.fillStyle='rgba(255,255,255,.35)';rr(c,x-18,y-12,36,12,6);c.fill()}
  steam(x:number,y:number){const c=this.ctx;c.strokeStyle='rgba(255,255,255,.75)';c.lineWidth=3;for(const dx of [-10,2,13]){c.beginPath();c.moveTo(x+dx,y-28);c.bezierCurveTo(x+dx-8,y-43,x+dx+8,y-48,x+dx,y-61);c.stroke()}}
  cat(x:number,y:number,cat:Customer,t:number){const c=this.ctx,shake=cat.mood==='impatient'?Math.sin(t*.035)*3:0;x+=shake;ellipse(c,x+48,y+69,78,15,'rgba(58,34,15,.17)');this.catFace(x+48,y+10,cat.kind,cat.mood);c.fillStyle='#6d3b1f';c.font='800 15px Arial';c.textAlign='center';c.fillText(cat.name,x+48,y-38);this.progress(x+3,y+55,90,13,cat.order.patience/cat.order.maxPatience,cat.order.patience/cat.order.maxPatience<.25?'#ef5757':'#77d94c');this.orderBubble(x+84,y-44,cat.order)}
  catFace(x:number,y:number,kind:CatKind,mood:Mood){const c=this.ctx,fur:{[k in CatKind]:string}={orange:'#f49a35',gray:'#9aa4ad',white:'#fff7ec',black:'#34303a',tabby:'#c99559'},stripe:{[k in CatKind]:string}={orange:'#d67523',gray:'#737d86',white:'#eadfd4',black:'#26222b',tabby:'#815b38'};c.fillStyle=fur[kind];c.beginPath();c.arc(x,y,37,0,7);c.fill();c.strokeStyle='rgba(88,50,28,.35)';c.lineWidth=2;c.stroke();c.fillStyle=fur[kind];c.beginPath();c.moveTo(x-25,y-24);c.lineTo(x-39,y-58);c.lineTo(x-8,y-37);c.fill();c.beginPath();c.moveTo(x+25,y-24);c.lineTo(x+39,y-58);c.lineTo(x+8,y-37);c.fill();c.fillStyle='#ffb7b4';c.beginPath();c.moveTo(x-27,y-32);c.lineTo(x-35,y-50);c.lineTo(x-14,y-38);c.fill();c.beginPath();c.moveTo(x+27,y-32);c.lineTo(x+35,y-50);c.lineTo(x+14,y-38);c.fill();c.strokeStyle=stripe[kind];c.lineWidth=3;for(const dx of[-14,0,14]){c.beginPath();c.moveTo(x+dx,y-35);c.lineTo(x+dx*.7,y-24);c.stroke()}c.fillStyle=kind==='black'?'#ffd36a':'#2a221d';if(mood==='happy'||mood==='served'){c.strokeStyle=c.fillStyle;c.lineWidth=4;c.beginPath();c.arc(x-14,y-5,7,0,Math.PI);c.stroke();c.beginPath();c.arc(x+14,y-5,7,0,Math.PI);c.stroke()}else{ellipse(c,x-14,y-6,7,mood==='impatient'?4:9,c.fillStyle as string);ellipse(c,x+14,y-6,7,mood==='impatient'?4:9,c.fillStyle as string);ellipse(c,x-17,y-9,2,2,'#fff');ellipse(c,x+11,y-9,2,2,'#fff')}ellipse(c,x,y+7,5,3,'#f26b75');c.strokeStyle='#57311f';c.lineWidth=2;c.beginPath();mood==='impatient'?c.arc(x,y+20,9,Math.PI,0):c.arc(x,y+13,11,0,Math.PI);c.stroke();c.strokeStyle='rgba(75,42,25,.55)';for(const side of[-1,1])for(let i=0;i<3;i++){c.beginPath();c.moveTo(x+side*8,y+8+i*5);c.lineTo(x+side*(30+i*4),y+4+i*3);c.stroke()}ellipse(c,x-26,y+9,8,5,'rgba(255,116,126,.25)');ellipse(c,x+26,y+9,8,5,'rgba(255,116,126,.25)')}
  orderBubble(x:number,y:number,o:Order){this.panel(x,y,92,72,16);let sx=x+25;for(const n of o.needs){this.item(n.type,sx,y+30,.45);this.ctx.fillStyle='#6d3b1f';this.ctx.font='800 16px Arial';this.ctx.textAlign='center';this.ctx.fillText(`${n.got}/${n.qty}`,sx,y+62);sx+=35}}
  tutorial(){const c=this.ctx;c.save();c.fillStyle='rgba(0,0,0,.28)';c.fillRect(0,0,this.w,this.h);this.panel(24,this.h*.38,this.w-48,132,22);c.fillStyle='#6d3b1f';c.textAlign='center';c.font='900 22px Arial';const lines=['Соедини 3 одинаковых лакомства','Выполняй заказы котиков','Длинные цепочки дают бонусы','Монеты трать на улучшения кафе'];c.fillText(lines[this.tut],this.w/2,this.h*.43);c.font='16px Arial';c.fillText('Нажми, чтобы продолжить',this.w/2,this.h*.49);c.restore()}
  pause(){this.logo(150);const c=this.ctx;c.textAlign='center';c.fillStyle='#6d3b1f';c.font='900 30px Arial';c.fillText('Пауза',this.w/2,222);this.button('resume','Продолжить',this.w/2-108,272,216,58);this.button('menu','Меню',this.w/2-108,346,216,54)}
  results(){this.panel(28,this.h*.18,this.w-56,this.h*.48,28);const c=this.ctx;c.fillStyle='#6d3b1f';c.textAlign='center';c.font='900 32px Arial';c.fillText('Смена завершена!',this.w/2,this.h*.25);for(let i=0;i<3;i++)this.star(this.w/2-50+i*50,this.h*.31,21);c.font='800 21px Arial';c.fillText(`Счёт: ${this.score}`,this.w/2,this.h*.39);c.fillText(`Монеты: +${this.runCoins}`,this.w/2,this.h*.44);c.fillText(`Заказы: ${this.served}`,this.w/2,this.h*.49);c.fillText(`Лучший: ${this.save.best}`,this.w/2,this.h*.54);this.button('play','Играть ещё',this.w/2-108,this.h*.69,216,54);this.button('x2','x2 монеты',this.w/2-108,this.h*.76,216,54,this.runCoins>0);this.button('shop','Улучшения',this.w/2-108,this.h*.83,216,54)}
  shop(){this.panel(18,76,this.w-36,this.h-158,24);const c=this.ctx;c.fillStyle='#6d3b1f';c.textAlign='center';c.font='900 28px Arial';c.fillText('Улучшения кафе',this.w/2,116);let y=140;for(const k of Object.keys(upgradeTitles)){const lvl=this.save.upgrades[k]||0,price=60*(lvl+1)*(lvl+1);this.panel(34,y,this.w-68,76,18);c.fillStyle='#6d3b1f';c.textAlign='left';c.font='800 17px Arial';c.fillText(`${upgradeTitles[k]}  ${lvl}/5`,52,y+25);c.font='14px Arial';c.fillText(k==='coffee'?'+ очки за кофе':k==='tables'?'+ терпение котиков':k==='dessert'?'+ монеты за десерты':k==='barista'?'помощь с заказами':k==='magnet'?'+ шанс бонусов':'+ монеты за рыбу',52,y+48);c.textAlign='right';c.font='900 17px Arial';c.fillText(lvl>=5?'MAX':String(price),this.w-54,y+28);this.button('buy','Купить',this.w-126,y+40,88,28,lvl<5&&this.save.coins>=price,k);y+=86}this.button('menu','Назад',24,this.h-68,122,48)}
  settings(){this.logo(104);const c=this.ctx;c.fillStyle='#6d3b1f';c.textAlign='center';c.font='900 26px Arial';c.fillText('Настройки',this.w/2,170);this.button('sound',`Звук: ${this.save.sound?'Вкл':'Выкл'}`,this.w/2-120,220,240,52);this.button('vibration',`Вибрация: ${this.save.vibration?'Вкл':'Выкл'}`,this.w/2-120,286,240,52);this.button('quality',`Качество: ${this.save.quality}`,this.w/2-120,352,240,52);this.button('menu','Назад',this.w/2-120,430,240,52)}
  records(){const c=this.ctx;c.fillStyle='#6d3b1f';c.textAlign='center';c.font='900 32px Arial';c.fillText('Рекорды',this.w/2,112);if(!this.leaderboard.length)this.leaderboard=[{rank:1,name:'Ты',score:this.save.best},{rank:2,name:'Рыжик',score:8500},{rank:3,name:'Белла',score:6200},{rank:4,name:'Мурзик',score:4800}];let y=165;c.font='800 20px Arial';for(const e of this.leaderboard){c.fillText(`${e.rank}. ${e.name} — ${e.score}`,this.w/2,y);y+=36}this.button('menu','Назад',this.w/2-105,this.h-88,210,54)}
  effects(){const c=this.ctx;for(const p of this.particles){c.save();c.globalAlpha=clamp(p.life/850,0,1);if(p.kind==='coin'){this.coin(p.x,p.y,8)}else if(p.kind==='heart'){c.fillStyle='#ff6f93';c.beginPath();c.moveTo(p.x,p.y+6);c.bezierCurveTo(p.x-14,p.y-6,p.x-6,p.y-16,p.x,p.y-7);c.bezierCurveTo(p.x+6,p.y-16,p.x+14,p.y-6,p.x,p.y+6);c.fill()}else ellipse(c,p.x,p.y,5,5,'#fff37c');c.restore()}for(const f of this.floats){c.save();c.globalAlpha=clamp(f.life/1000,0,1);c.font='900 23px Arial';c.textAlign='center';c.strokeStyle='rgba(92,46,12,.55)';c.lineWidth=5;c.strokeText(f.text,f.x,f.y);c.fillStyle=f.color;c.fillText(f.text,f.x,f.y);c.restore()}}
  coin(x:number,y:number,r:number){const c=this.ctx,g=c.createRadialGradient(x-r*.3,y-r*.4,r*.1,x,y,r);g.addColorStop(0,'#fff7a8');g.addColorStop(.45,'#ffd45a');g.addColorStop(1,'#c97d17');ellipse(c,x,y,r,r,g);c.strokeStyle='#8a5310';c.lineWidth=2;c.stroke();ellipse(c,x,y,r*.45,r*.45,'#d78a1b')}
  star(x:number,y:number,r:number){const c=this.ctx;c.save();c.translate(x,y);c.fillStyle='#ffd64e';c.strokeStyle='#b66d16';c.lineWidth=2;c.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rrr=i%2?r:r*.45;c.lineTo(Math.cos(a)*rrr,Math.sin(a)*rrr)}c.closePath();c.fill();c.stroke();c.restore()}
}
