import './styles.css';

type T='coffee'|'tea'|'milk'|'croissant'|'cake'|'cookie'|'fish'|'dessert';
type C={t:T;x:number;y:number;sel:boolean};
const canvas=document.querySelector<HTMLCanvasElement>('#game')!,ctx=canvas.getContext('2d')!;
const types:T[]=['coffee','tea','milk','croissant','cake','cookie','fish','dessert'];
const icon:Record<T,string>={coffee:'☕',tea:'🍵',milk:'🥛',croissant:'🥐',cake:'🍰',cookie:'🍪',fish:'🐟',dessert:'🍓'};
let W=0,H=0,dpr=1,screen='menu',board:C[][]=[],chain:C[]=[],drag=false,score=0,coins=Number(localStorage.catCoins||120),best=Number(localStorage.catBest||0),day=Number(localStorage.catDay||1),time=75,last=0,combo=0,served=0;
let cats:{name:string;color:string,mood:string,pat:number,max:number,need:T,count:number,have:number}[]=[];
let buttons:{x:number;y:number;w:number;h:number;id:string}[]=[];
const names=['Рыжик','Белла','Мурзик','Пуша','Барсик'],colors=['#f59b34','#aaa','#fff1df','#4e4549','#c99b64'];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function save(){localStorage.catCoins=coins;localStorage.catBest=best;localStorage.catDay=day}
function avail(){return types.slice(0,day>=15?8:day>=7?6:day>=3?5:day>=2?4:3)}
function rnd<T>(a:T[]){return a[Math.random()*a.length|0]}
function cell(x:number,y:number):C{return{t:rnd(avail()),x,y,sel:false}}
function newBoard(){board=[];for(let y=0;y<6;y++){board[y]=[];for(let x=0;x<6;x++)board[y][x]=cell(x,y)}}
function addCats(){while(cats.length<(day>=10?3:2)){let n=rnd(avail());cats.push({name:rnd(names),color:rnd(colors),mood:'waiting',pat:25,max:25,need:n,count:1+(Math.random()*3|0),have:0})}}
function start(){score=0;combo=0;served=0;time=day<3?60:75;cats=[];newBoard();addCats();screen='play'}
function g(){let size=Math.min(W-28,H*.55,620),s=size/6;return{x:(W-size)/2,y:H*.38,s,size}}
function at(px:number,py:number){let a=g(),x=Math.floor((px-a.x)/a.s),y=Math.floor((py-a.y)/a.s);return x>=0&&x<6&&y>=0&&y<6?board[y][x]:null}
function near(a:C,b:C){return Math.abs(a.x-b.x)<=1&&Math.abs(a.y-b.y)<=1&&(a!==b)}
function collapse(){for(let x=0;x<6;x++){let w=5;for(let y=5;y>=0;y--){if(board[y][x]){board[w][x]=board[y][x];board[w][x].y=w;w--}}for(let y=w;y>=0;y--)board[y][x]=cell(x,y)}}
function release(){if(chain.length>=3){let t=chain[0].t,n=chain.length;score+=n*10+(n>3?30:0)+(n>5?100:0);for(let c of cats){if(c.need===t){c.have=Math.min(c.count,c.have+n);if(c.have>=c.count){served++;combo++;coins+=8+combo;c.mood='happy';setTimeout(()=>{cats=cats.filter(k=>k!==c);addCats()},350)}}}for(let c of chain)board[c.y][c.x]=null as any;collapse()}for(let c of chain)c.sel=false;chain=[]}
canvas.onpointerdown=e=>{let p=pos(e),b=buttons.find(q=>p.x>=q.x&&p.x<=q.x+q.w&&p.y>=q.y&&p.y<=q.y+q.h);if(b){click(b.id);return}if(screen==='play'){let c=at(p.x,p.y);if(c){drag=true;chain=[c];c.sel=true}}};
canvas.onpointermove=e=>{if(!drag)return;let c=at(pos(e).x,pos(e).y),l=chain[chain.length-1];if(c&&l&&c.t===l.t&&near(c,l)&&!chain.includes(c)){chain.push(c);c.sel=true}};
canvas.onpointerup=()=>{if(drag)release();drag=false};
function pos(e:PointerEvent){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function click(id:string){if(id==='play')start();if(id==='menu'){screen='menu';save()}if(id==='shop')screen='shop';if(id==='again'){day++;save();start()}if(id==='pause')screen='pause';if(id==='resume')screen='play';if(id==='x2'){coins+=Math.max(10,served*8);save()}}
function bg(){let gr=ctx.createLinearGradient(0,0,0,H);gr.addColorStop(0,'#f7cf90');gr.addColorStop(.6,'#fee9cc');gr.addColorStop(1,'#d99255');ctx.fillStyle=gr;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.35)';round(W*.08,H*.08,W*.34,H*.15,25,1);ctx.fillStyle='#8a4b25';ctx.font='bold 22px Arial';ctx.fillText('Кофе ♥ Котики',W*.12,H*.15)}
function round(x:number,y:number,w:number,h:number,r:number,f=0){ctx.beginPath();ctx.roundRect(x,y,w,h,r);f?ctx.fill():ctx.stroke()}
function panel(x:number,y:number,w:number,h:number){ctx.save();ctx.shadowColor='#8b5b2d66';ctx.shadowBlur=18;ctx.shadowOffsetY=8;ctx.fillStyle='#fff1d6';round(x,y,w,h,22,1);ctx.strokeStyle='#b87235';ctx.lineWidth=3;round(x,y,w,h,22);ctx.restore()}
function btn(x:number,y:number,w:number,h:number,id:string,txt:string,green=false){buttons.push({x,y,w,h,id});let gr=ctx.createLinearGradient(x,y,x,y+h);gr.addColorStop(0,green?'#9be76d':'#ffd37b');gr.addColorStop(1,green?'#39ad48':'#e99035');ctx.fillStyle=gr;round(x,y,w,h,18,1);ctx.fillStyle='#fff';ctx.font='bold 22px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(txt,x+w/2,y+h/2)}
function cat(x:number,y:number,c:any){panel(x-65,y-5,130,105);ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(x,y+38,36,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(x-26,y+18);ctx.lineTo(x-15,y-12);ctx.lineTo(x,y+20);ctx.moveTo(x+26,y+18);ctx.lineTo(x+15,y-12);ctx.lineTo(x,y+20);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x-13,y+36,8,0,7);ctx.arc(x+13,y+36,8,0,7);ctx.fill();ctx.fillStyle='#3b2418';ctx.beginPath();ctx.arc(x-13,y+37,4,0,7);ctx.arc(x+13,y+37,4,0,7);ctx.fill();ctx.fillStyle='#7b431f';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(c.name,x,y+88);ctx.fillText(icon[c.need]+' '+c.have+'/'+c.count,x+58,y+33)}
function item(c:C,x:number,y:number,s:number){ctx.save();ctx.translate(x,y);ctx.shadowColor=c.sel?'#36b6ff':'#5a351855';ctx.shadowBlur=c.sel?18:8;ctx.fillStyle='#fff6df';ctx.beginPath();ctx.ellipse(0,s*.17,s*.42,s*.22,0,0,7);ctx.fill();ctx.shadowBlur=0;ctx.font=s*.55+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icon[c.t],0,-2);ctx.restore()}
function play(){bg();panel(12,10,W-24,72);ctx.fillStyle='#743f1f';ctx.font='bold 19px Arial';ctx.textAlign='left';ctx.fillText('⭐ '+score,28,42);ctx.fillText('⏱ '+Math.ceil(time),W*.33,42);ctx.fillText('🐾 '+coins,W*.56,42);ctx.fillText('День '+day,W*.76,42);btn(W-68,22,44,40,'pause','Ⅱ');cats.forEach((c,i)=>cat(W/(cats.length+1)*(i+1),96,c));let a=g();panel(a.x-8,a.y-8,a.size+16,a.size+16);for(let y=0;y<6;y++)for(let x=0;x<6;x++){ctx.fillStyle='#ffffff77';round(a.x+x*a.s+3,a.y+y*a.s+3,a.s-6,a.s-6,14,1);item(board[y][x],a.x+(x+.5)*a.s,a.y+(y+.5)*a.s,a.s*.78)}if(chain.length>1){ctx.strokeStyle='#fff36b';ctx.lineWidth=8;ctx.beginPath();chain.forEach((c,i)=>{let x=a.x+(c.x+.5)*a.s,y=a.y+(c.y+.5)*a.s;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}btn(18,H-76,W*.28,56,'hint','Подсказка');btn(W*.36,H-76,W*.28,56,'mix','Микс');btn(W*.69,H-76,W*.28,56,'boost','Буст')}
function menu(){bg();panel(W*.08,H*.13,W*.84,H*.3);ctx.textAlign='center';ctx.fillStyle='#743f1f';ctx.font='bold 40px Arial';ctx.fillText('🐾 Котокафе 🐾',W/2,H*.22);ctx.font='bold 24px Arial';ctx.fillText('Match & Serve',W/2,H*.28);btn(W*.18,H*.48,W*.64,62,'play','Играть',true);btn(W*.18,H*.58,W*.64,54,'shop','Улучшения');ctx.fillStyle='#743f1f';ctx.font='bold 19px Arial';ctx.fillText('Монеты: '+coins+'  Лучший: '+best+'  День: '+day,W/2,H*.78)}
function results(){bg();panel(W*.1,H*.2,W*.8,H*.52);ctx.textAlign='center';ctx.fillStyle='#743f1f';ctx.font='bold 34px Arial';ctx.fillText('Смена завершена!',W/2,H*.29);ctx.font='22px Arial';ctx.fillText('Счёт: '+score,W/2,H*.4);ctx.fillText('Заказы: '+served,W/2,H*.47);ctx.fillText('Монеты: '+coins,W/2,H*.54);btn(W*.18,H*.73,W*.64,58,'again','Играть ещё',true);btn(W*.18,H*.82,W*.64,50,'x2','x2 монеты за рекламу')}
function shop(){bg();panel(18,25,W-36,H-50);ctx.textAlign='center';ctx.fillStyle='#743f1f';ctx.font='bold 30px Arial';ctx.fillText('Улучшения кафе',W/2,70);['Кофемашина','Уютные столики','Витрина десертов','Помощник-бариста','Магнит лакомств'].forEach((t,i)=>{ctx.fillStyle='#fff7e6';round(34,105+i*72,W-68,56,16,1);ctx.fillStyle='#6e3d1e';ctx.font='bold 17px Arial';ctx.textAlign='left';ctx.fillText(t,50,139);ctx.textAlign='right';ctx.fillText(String(70*(i+1)),W-55,139)});btn(30,H-75,130,48,'menu','Назад')}
function pause(){play();panel(W*.16,H*.35,W*.68,H*.25);ctx.textAlign='center';ctx.fillStyle='#743f1f';ctx.font='bold 32px Arial';ctx.fillText('Пауза',W/2,H*.43);btn(W*.25,H*.49,W*.5,55,'resume','Продолжить',true)}
function tick(dt:number){if(screen==='play'){time-=dt;if(time<=0){best=Math.max(best,score);save();screen='results'}cats.forEach(c=>{c.pat-=dt;if(c.pat<=0){combo=0;cats=cats.filter(k=>k!==c);addCats()}})}}
function loop(t=0){let dt=Math.min(.033,(t-last)/1000||.016);last=t;buttons=[];tick(dt);if(screen==='menu')menu();else if(screen==='play')play();else if(screen==='pause')pause();else if(screen==='shop')shop();else results();requestAnimationFrame(loop)}loop();
